// AUTO-GENERATED from players_2026.csv – Real IPL 2026 squads
const SQUAD_DATA_2026 = {
  "Chennai Super Kings": [
    {
      "player": "Ruturaj Gaikwad",
      "role": "Batsman",
      "age": 28,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 18.0,
      "is_captain": true,
      "is_retained": true
    },
    {
      "player": "MS Dhoni",
      "role": "WK-Batsman",
      "age": 44,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Medium",
      "is_overseas": false,
      "price_cr": 4.0,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Sanju Samson",
      "role": "WK-Batsman",
      "age": 30,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 14.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Dewald Brevis",
      "role": "Allrounder",
      "age": 22,
      "nationality": "South Africa",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": true,
      "price_cr": 8.4,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Ayush Mhatre",
      "role": "Batsman",
      "age": 18,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 14.2,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Kartik Sharma",
      "role": "WK-Batsman",
      "age": 20,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 14.2,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Sarfaraz Khan",
      "role": "Batsman",
      "age": 27,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 2.6,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Urvil Patel",
      "role": "WK-Batsman",
      "age": 25,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 1.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Anshul Kamboj",
      "role": "Allrounder",
      "age": 24,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 3.4,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Jamie Overton",
      "role": "Allrounder",
      "age": 29,
      "nationality": "England",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": true,
      "price_cr": 2.2,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Ramakrishna Ghosh",
      "role": "Allrounder",
      "age": 22,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 1.5,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Prashant Veer",
      "role": "Allrounder",
      "age": 26,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Medium",
      "is_overseas": false,
      "price_cr": 14.2,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Matthew Short",
      "role": "Allrounder",
      "age": 28,
      "nationality": "Australia",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": true,
      "price_cr": 1.6,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Aman Khan",
      "role": "Batsman",
      "age": 23,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 1.2,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Zak Foulkes",
      "role": "Allrounder",
      "age": 23,
      "nationality": "England",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": true,
      "price_cr": 1.2,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Shivam Dube",
      "role": "Allrounder",
      "age": 31,
      "nationality": "India",
      "batting_style": "Left Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 12.0,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Khaleel Ahmed",
      "role": "Bowler",
      "age": 27,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Left Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 5.25,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Noor Ahmad",
      "role": "Bowler",
      "age": 21,
      "nationality": "Afghanistan",
      "batting_style": "Right Hand",
      "bowling_style": "Left Arm Chinaman",
      "is_overseas": true,
      "price_cr": 10.75,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Mukesh Choudhary",
      "role": "Bowler",
      "age": 28,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Left Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Nathan Ellis",
      "role": "Bowler",
      "age": 30,
      "nationality": "Australia",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": true,
      "price_cr": 2.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Shreyas Gopal",
      "role": "Allrounder",
      "age": 31,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Leg Break",
      "is_overseas": false,
      "price_cr": 1.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Gurjapneet Singh",
      "role": "Bowler",
      "age": 23,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Left Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Akeal Hosein",
      "role": "Bowler",
      "age": 30,
      "nationality": "West Indies",
      "batting_style": "Right Hand",
      "bowling_style": "Left Arm Spin",
      "is_overseas": true,
      "price_cr": 1.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Matt Henry",
      "role": "Bowler",
      "age": 33,
      "nationality": "New Zealand",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": true,
      "price_cr": 2.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Rahul Chahar",
      "role": "Bowler",
      "age": 25,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Leg Break",
      "is_overseas": false,
      "price_cr": 1.0,
      "is_captain": false,
      "is_retained": false
    }
  ],
  "Mumbai Indians": [
    {
      "player": "Rohit Sharma",
      "role": "Batsman",
      "age": 38,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 16.3,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Suryakumar Yadav",
      "role": "Batsman",
      "age": 34,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 16.35,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Robin Minz",
      "role": "WK-Batsman",
      "age": 21,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 3.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Sherfane Rutherford",
      "role": "Batsman",
      "age": 28,
      "nationality": "West Indies",
      "batting_style": "Left Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": true,
      "price_cr": 2.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Ryan Rickelton",
      "role": "WK-Batsman",
      "age": 26,
      "nationality": "South Africa",
      "batting_style": "Left Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": true,
      "price_cr": 1.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Quinton de Kock",
      "role": "WK-Batsman",
      "age": 33,
      "nationality": "South Africa",
      "batting_style": "Left Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": true,
      "price_cr": 1.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Danish Malewar",
      "role": "Batsman",
      "age": 25,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 0.4,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Tilak Varma",
      "role": "Batsman",
      "age": 22,
      "nationality": "India",
      "batting_style": "Left Hand",
      "bowling_style": "Left Arm Spin",
      "is_overseas": false,
      "price_cr": 17.0,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Hardik Pandya",
      "role": "Allrounder",
      "age": 31,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 16.35,
      "is_captain": true,
      "is_retained": true
    },
    {
      "player": "Naman Dhir",
      "role": "Allrounder",
      "age": 24,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 5.5,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Mitchell Santner",
      "role": "Allrounder",
      "age": 33,
      "nationality": "New Zealand",
      "batting_style": "Left Hand",
      "bowling_style": "Left Arm Spin",
      "is_overseas": true,
      "price_cr": 2.6,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Raj Angad Bawa",
      "role": "Allrounder",
      "age": 23,
      "nationality": "India",
      "batting_style": "Left Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 1.5,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Atharva Ankolekar",
      "role": "Allrounder",
      "age": 26,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Mayank Rawat",
      "role": "Batsman",
      "age": 22,
      "nationality": "India",
      "batting_style": "Left Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Corbin Bosch",
      "role": "Allrounder",
      "age": 30,
      "nationality": "South Africa",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": true,
      "price_cr": 1.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Will Jacks",
      "role": "Allrounder",
      "age": 26,
      "nationality": "England",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": true,
      "price_cr": 1.4,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Shardul Thakur",
      "role": "Allrounder",
      "age": 33,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 4.2,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Jasprit Bumrah",
      "role": "Bowler",
      "age": 31,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast",
      "is_overseas": false,
      "price_cr": 18.0,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Trent Boult",
      "role": "Bowler",
      "age": 36,
      "nationality": "New Zealand",
      "batting_style": "Right Hand",
      "bowling_style": "Left Arm Fast Medium",
      "is_overseas": true,
      "price_cr": 12.5,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Deepak Chahar",
      "role": "Bowler",
      "age": 32,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 4.2,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Mayank Markande",
      "role": "Bowler",
      "age": 26,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Leg Break",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Ashwani Kumar",
      "role": "Bowler",
      "age": 22,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Mohammad Izhar",
      "role": "Bowler",
      "age": 21,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Raghu Sharma",
      "role": "Bowler",
      "age": 24,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Leg Break",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    }
  ],
  "Royal Challengers Bengaluru": [
    {
      "player": "Virat Kohli",
      "role": "Batsman",
      "age": 37,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 21.0,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Phil Salt",
      "role": "WK-Batsman",
      "age": 28,
      "nationality": "England",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": true,
      "price_cr": 11.5,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Devdutt Padikkal",
      "role": "Batsman",
      "age": 25,
      "nationality": "India",
      "batting_style": "Left Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 14.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Rajat Patidar",
      "role": "Batsman",
      "age": 32,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 11.0,
      "is_captain": true,
      "is_retained": true
    },
    {
      "player": "Jitesh Sharma",
      "role": "WK-Batsman",
      "age": 30,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 11.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Jordan Cox",
      "role": "WK-Batsman",
      "age": 24,
      "nationality": "England",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": true,
      "price_cr": 0.75,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Krunal Pandya",
      "role": "Allrounder",
      "age": 34,
      "nationality": "India",
      "batting_style": "Left Hand",
      "bowling_style": "Left Arm Spin",
      "is_overseas": false,
      "price_cr": 5.75,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Tim David",
      "role": "Allrounder",
      "age": 29,
      "nationality": "Singapore",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": true,
      "price_cr": 3.4,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Romario Shepherd",
      "role": "Allrounder",
      "age": 29,
      "nationality": "West Indies",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": true,
      "price_cr": 1.5,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Jacob Bethell",
      "role": "Allrounder",
      "age": 22,
      "nationality": "England",
      "batting_style": "Left Hand",
      "bowling_style": "Left Arm Spin",
      "is_overseas": true,
      "price_cr": 2.8,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Venkatesh Iyer",
      "role": "Allrounder",
      "age": 30,
      "nationality": "India",
      "batting_style": "Left Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 23.75,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Satvik Deswal",
      "role": "Allrounder",
      "age": 20,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Mangesh Yadav",
      "role": "Bowler",
      "age": 22,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Leg Break",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Vicky Ostwal",
      "role": "Bowler",
      "age": 23,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Leg Break",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Vihaan Malhotra",
      "role": "Batsman",
      "age": 19,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Kanishk Chouhan",
      "role": "Bowler",
      "age": 22,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Bhuvneshwar Kumar",
      "role": "Bowler",
      "age": 35,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 10.75,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Josh Hazlewood",
      "role": "Bowler",
      "age": 34,
      "nationality": "Australia",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": true,
      "price_cr": 12.5,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Yash Dayal",
      "role": "Bowler",
      "age": 26,
      "nationality": "India",
      "batting_style": "Left Hand",
      "bowling_style": "Left Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 5.0,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Nuwan Thushara",
      "role": "Bowler",
      "age": 27,
      "nationality": "Sri Lanka",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": true,
      "price_cr": 0.75,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Suyash Sharma",
      "role": "Bowler",
      "age": 23,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Leg Break",
      "is_overseas": false,
      "price_cr": 2.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Rasikh Dar",
      "role": "Bowler",
      "age": 23,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Jacob Duffy",
      "role": "Bowler",
      "age": 31,
      "nationality": "New Zealand",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": true,
      "price_cr": 0.5,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Abhinandan Singh",
      "role": "Bowler",
      "age": 22,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    }
  ],
  "Kolkata Knight Riders": [
    {
      "player": "Ajinkya Rahane",
      "role": "Batsman",
      "age": 37,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 1.5,
      "is_captain": true,
      "is_retained": true
    },
    {
      "player": "Angkrish Raghuvanshi",
      "role": "Batsman",
      "age": 19,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 3.0,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Manish Pandey",
      "role": "Batsman",
      "age": 35,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Rinku Singh",
      "role": "Batsman",
      "age": 27,
      "nationality": "India",
      "batting_style": "Left Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 13.0,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Rovman Powell",
      "role": "Batsman",
      "age": 31,
      "nationality": "West Indies",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": true,
      "price_cr": 0.75,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Finn Allen",
      "role": "WK-Batsman",
      "age": 27,
      "nationality": "New Zealand",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": true,
      "price_cr": 2.4,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Tim Seifert",
      "role": "WK-Batsman",
      "age": 30,
      "nationality": "New Zealand",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": true,
      "price_cr": 1.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Tejasvi Singh",
      "role": "WK-Batsman",
      "age": 21,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Rahul Tripathi",
      "role": "Batsman",
      "age": 34,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Cameron Green",
      "role": "Allrounder",
      "age": 26,
      "nationality": "Australia",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": true,
      "price_cr": 18.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Anukul Roy",
      "role": "Allrounder",
      "age": 26,
      "nationality": "India",
      "batting_style": "Left Hand",
      "bowling_style": "Left Arm Spin",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Sarthak Ranjan",
      "role": "Allrounder",
      "age": 22,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Daksh Kamra",
      "role": "Allrounder",
      "age": 21,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Rachin Ravindra",
      "role": "Allrounder",
      "age": 26,
      "nationality": "New Zealand",
      "batting_style": "Left Hand",
      "bowling_style": "Left Arm Spin",
      "is_overseas": true,
      "price_cr": 1.2,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Ramandeep Singh",
      "role": "Allrounder",
      "age": 27,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 4.2,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Vaibhav Arora",
      "role": "Bowler",
      "age": 27,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 1.8,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Matheesha Pathirana",
      "role": "Bowler",
      "age": 22,
      "nationality": "Sri Lanka",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast",
      "is_overseas": true,
      "price_cr": 18.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Kartik Tyagi",
      "role": "Bowler",
      "age": 24,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 0.5,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Prashant Solanki",
      "role": "Bowler",
      "age": 26,
      "nationality": "India",
      "batting_style": "Left Hand",
      "bowling_style": "Left Arm Spin",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Harshit Rana",
      "role": "Bowler",
      "age": 23,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast",
      "is_overseas": false,
      "price_cr": 4.0,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Umran Malik",
      "role": "Bowler",
      "age": 25,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Sunil Narine",
      "role": "Allrounder",
      "age": 36,
      "nationality": "West Indies",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": true,
      "price_cr": 12.0,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Varun Chakravarthy",
      "role": "Bowler",
      "age": 33,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Mystery Spin",
      "is_overseas": false,
      "price_cr": 12.0,
      "is_captain": false,
      "is_retained": true
    }
  ],
  "Sunrisers Hyderabad": [
    {
      "player": "Pat Cummins",
      "role": "Bowler",
      "age": 32,
      "nationality": "Australia",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast",
      "is_overseas": true,
      "price_cr": 18.5,
      "is_captain": true,
      "is_retained": true
    },
    {
      "player": "Ishan Kishan",
      "role": "WK-Batsman",
      "age": 27,
      "nationality": "India",
      "batting_style": "Left Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 11.25,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Aniket Verma",
      "role": "Batsman",
      "age": 23,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 3.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Smaran Ravichandran",
      "role": "Batsman",
      "age": 22,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Salil Arora",
      "role": "WK-Batsman",
      "age": 24,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Heinrich Klaasen",
      "role": "WK-Batsman",
      "age": 33,
      "nationality": "South Africa",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": true,
      "price_cr": 23.0,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Travis Head",
      "role": "Batsman",
      "age": 31,
      "nationality": "Australia",
      "batting_style": "Left Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": true,
      "price_cr": 14.0,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Harshal Patel",
      "role": "Bowler",
      "age": 34,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 4.2,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Kamindu Mendis",
      "role": "Allrounder",
      "age": 26,
      "nationality": "Sri Lanka",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": true,
      "price_cr": 4.8,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Harsh Dubey",
      "role": "Allrounder",
      "age": 24,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 1.5,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Brydon Carse",
      "role": "Allrounder",
      "age": 29,
      "nationality": "England",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast",
      "is_overseas": true,
      "price_cr": 0.75,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Shivang Kumar",
      "role": "Batsman",
      "age": 21,
      "nationality": "India",
      "batting_style": "Left Hand",
      "bowling_style": "Left Arm Spin",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Liam Livingstone",
      "role": "Allrounder",
      "age": 32,
      "nationality": "England",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Leg Break",
      "is_overseas": true,
      "price_cr": 8.5,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Jack Edwards",
      "role": "Allrounder",
      "age": 25,
      "nationality": "Australia",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": true,
      "price_cr": 0.75,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Abhishek Sharma",
      "role": "Allrounder",
      "age": 24,
      "nationality": "India",
      "batting_style": "Left Hand",
      "bowling_style": "Left Arm Spin",
      "is_overseas": false,
      "price_cr": 14.0,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Nitish Kumar Reddy",
      "role": "Allrounder",
      "age": 21,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 13.0,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Zeeshan Ansari",
      "role": "Bowler",
      "age": 23,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Left Arm Spin",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Jaydev Unadkat",
      "role": "Bowler",
      "age": 33,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Left Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 1.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Eshan Malinga",
      "role": "Bowler",
      "age": 24,
      "nationality": "Sri Lanka",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": true,
      "price_cr": 0.4,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Sakib Hussain",
      "role": "Bowler",
      "age": 23,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Shivam Mavi",
      "role": "Bowler",
      "age": 27,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast",
      "is_overseas": false,
      "price_cr": 1.0,
      "is_captain": false,
      "is_retained": false
    }
  ],
  "Delhi Capitals": [
    {
      "player": "Axar Patel",
      "role": "Allrounder",
      "age": 31,
      "nationality": "India",
      "batting_style": "Left Hand",
      "bowling_style": "Left Arm Spin",
      "is_overseas": false,
      "price_cr": 16.5,
      "is_captain": true,
      "is_retained": true
    },
    {
      "player": "KL Rahul",
      "role": "WK-Batsman",
      "age": 32,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 14.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Karun Nair",
      "role": "Batsman",
      "age": 33,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "David Miller",
      "role": "Batsman",
      "age": 35,
      "nationality": "South Africa",
      "batting_style": "Left Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": true,
      "price_cr": 3.4,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Ben Duckett",
      "role": "WK-Batsman",
      "age": 30,
      "nationality": "England",
      "batting_style": "Left Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": true,
      "price_cr": 0.75,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Pathum Nissanka",
      "role": "Batsman",
      "age": 27,
      "nationality": "Sri Lanka",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": true,
      "price_cr": 3.6,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Sahil Parakh",
      "role": "Batsman",
      "age": 21,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Prithvi Shaw",
      "role": "Batsman",
      "age": 25,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 7.5,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Abishek Porel",
      "role": "WK-Batsman",
      "age": 22,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 4.0,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Tristan Stubbs",
      "role": "WK-Batsman",
      "age": 24,
      "nationality": "South Africa",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": true,
      "price_cr": 1.2,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Sameer Rizvi",
      "role": "Allrounder",
      "age": 21,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 8.4,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Ashutosh Sharma",
      "role": "Allrounder",
      "age": 23,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 3.8,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Vipraj Nigam",
      "role": "Allrounder",
      "age": 22,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Ajay Mandal",
      "role": "Allrounder",
      "age": 26,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Left Arm Spin",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Tripurana Vijay",
      "role": "Allrounder",
      "age": 21,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Madhav Tiwari",
      "role": "Allrounder",
      "age": 22,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Auqib Dar",
      "role": "Bowler",
      "age": 23,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Nitish Rana",
      "role": "Allrounder",
      "age": 30,
      "nationality": "India",
      "batting_style": "Left Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 4.2,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Mitchell Starc",
      "role": "Bowler",
      "age": 35,
      "nationality": "Australia",
      "batting_style": "Right Hand",
      "bowling_style": "Left Arm Fast",
      "is_overseas": true,
      "price_cr": 11.5,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "T. Natarajan",
      "role": "Bowler",
      "age": 34,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Left Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 10.75,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Mukesh Kumar",
      "role": "Bowler",
      "age": 28,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 2.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Dushmantha Chameera",
      "role": "Bowler",
      "age": 33,
      "nationality": "Sri Lanka",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast",
      "is_overseas": true,
      "price_cr": 0.75,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Lungi Ngidi",
      "role": "Bowler",
      "age": 29,
      "nationality": "South Africa",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast",
      "is_overseas": true,
      "price_cr": 1.2,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Kyle Jamieson",
      "role": "Bowler",
      "age": 30,
      "nationality": "New Zealand",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": true,
      "price_cr": 1.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Kuldeep Yadav",
      "role": "Bowler",
      "age": 30,
      "nationality": "India",
      "batting_style": "Left Hand",
      "bowling_style": "Left Arm Chinaman",
      "is_overseas": false,
      "price_cr": 7.0,
      "is_captain": false,
      "is_retained": false
    }
  ],
  "Lucknow Super Giants": [
    {
      "player": "Rishabh Pant",
      "role": "WK-Batsman",
      "age": 28,
      "nationality": "India",
      "batting_style": "Left Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 27.0,
      "is_captain": true,
      "is_retained": true
    },
    {
      "player": "Aiden Markram",
      "role": "Batsman",
      "age": 30,
      "nationality": "South Africa",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": true,
      "price_cr": 2.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Himmat Singh",
      "role": "Batsman",
      "age": 27,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Matthew Breetzke",
      "role": "Batsman",
      "age": 25,
      "nationality": "South Africa",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": true,
      "price_cr": 0.75,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Mukul Choudhary",
      "role": "WK-Batsman",
      "age": 22,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Akshat Raghuwanshi",
      "role": "Batsman",
      "age": 20,
      "nationality": "India",
      "batting_style": "Left Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Josh Inglis",
      "role": "WK-Batsman",
      "age": 30,
      "nationality": "Australia",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": true,
      "price_cr": 0.75,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Nicholas Pooran",
      "role": "WK-Batsman",
      "age": 29,
      "nationality": "West Indies",
      "batting_style": "Left Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": true,
      "price_cr": 21.0,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Mitchell Marsh",
      "role": "Allrounder",
      "age": 33,
      "nationality": "Australia",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": true,
      "price_cr": 1.4,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Abdul Samad",
      "role": "Allrounder",
      "age": 24,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 4.2,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Shahbaz Ahmed",
      "role": "Allrounder",
      "age": 28,
      "nationality": "India",
      "batting_style": "Left Hand",
      "bowling_style": "Left Arm Spin",
      "is_overseas": false,
      "price_cr": 3.8,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Arshin Kulkarni",
      "role": "Allrounder",
      "age": 19,
      "nationality": "India",
      "batting_style": "Left Hand",
      "bowling_style": "Left Arm Spin",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Wanindu Hasaranga",
      "role": "Allrounder",
      "age": 27,
      "nationality": "Sri Lanka",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Leg Break",
      "is_overseas": true,
      "price_cr": 4.25,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Ayush Badoni",
      "role": "Allrounder",
      "age": 25,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 4.6,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Mohammad Shami",
      "role": "Bowler",
      "age": 34,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 10.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Avesh Khan",
      "role": "Bowler",
      "age": 28,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast",
      "is_overseas": false,
      "price_cr": 9.75,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "M. Siddharth",
      "role": "Bowler",
      "age": 26,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Digvesh Singh",
      "role": "Bowler",
      "age": 21,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Akash Singh",
      "role": "Bowler",
      "age": 22,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Left Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Prince Yadav",
      "role": "Bowler",
      "age": 21,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Arjun Tendulkar",
      "role": "Bowler",
      "age": 26,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Left Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Anrich Nortje",
      "role": "Bowler",
      "age": 31,
      "nationality": "South Africa",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast",
      "is_overseas": true,
      "price_cr": 6.5,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Naman Tiwari",
      "role": "Bowler",
      "age": 21,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Mayank Yadav",
      "role": "Bowler",
      "age": 23,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast",
      "is_overseas": false,
      "price_cr": 11.0,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Mohsin Khan",
      "role": "Bowler",
      "age": 26,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Left Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 2.0,
      "is_captain": false,
      "is_retained": false
    }
  ],
  "Rajasthan Royals": [
    {
      "player": "Riyan Parag",
      "role": "Allrounder",
      "age": 23,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 14.0,
      "is_captain": true,
      "is_retained": true
    },
    {
      "player": "Shubham Dubey",
      "role": "Batsman",
      "age": 24,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 7.4,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Vaibhav Suryavanshi",
      "role": "Batsman",
      "age": 14,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 1.1,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Donovan Ferreira",
      "role": "WK-Batsman",
      "age": 25,
      "nationality": "South Africa",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": true,
      "price_cr": 1.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Lhuan-dre Pretorius",
      "role": "WK-Batsman",
      "age": 22,
      "nationality": "South Africa",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": true,
      "price_cr": 1.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Ravi Singh",
      "role": "Batsman",
      "age": 23,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Aman Rao Perala",
      "role": "Batsman",
      "age": 22,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Shimron Hetmyer",
      "role": "Batsman",
      "age": 27,
      "nationality": "West Indies",
      "batting_style": "Left Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": true,
      "price_cr": 8.5,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Yashasvi Jaiswal",
      "role": "Batsman",
      "age": 23,
      "nationality": "India",
      "batting_style": "Left Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 18.0,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Dhruv Jurel",
      "role": "WK-Batsman",
      "age": 24,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 14.0,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Yudhvir Singh Charak",
      "role": "Allrounder",
      "age": 22,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Ravindra Jadeja",
      "role": "Allrounder",
      "age": 36,
      "nationality": "India",
      "batting_style": "Left Hand",
      "bowling_style": "Left Arm Spin",
      "is_overseas": false,
      "price_cr": 18.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Sam Curran",
      "role": "Allrounder",
      "age": 27,
      "nationality": "England",
      "batting_style": "Left Hand",
      "bowling_style": "Left Arm Fast Medium",
      "is_overseas": true,
      "price_cr": 2.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Jofra Archer",
      "role": "Bowler",
      "age": 30,
      "nationality": "England",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast",
      "is_overseas": true,
      "price_cr": 17.5,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Tushar Deshpande",
      "role": "Bowler",
      "age": 30,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 1.5,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Kwena Maphaka",
      "role": "Bowler",
      "age": 20,
      "nationality": "South Africa",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast",
      "is_overseas": true,
      "price_cr": 1.5,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Ravi Bishnoi",
      "role": "Bowler",
      "age": 24,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Leg Break",
      "is_overseas": false,
      "price_cr": 11.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Sushant Mishra",
      "role": "Bowler",
      "age": 22,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Yash Raj Punia",
      "role": "Bowler",
      "age": 21,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Vignesh Puthur",
      "role": "Bowler",
      "age": 23,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Brijesh Sharma",
      "role": "Bowler",
      "age": 24,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Adam Milne",
      "role": "Bowler",
      "age": 32,
      "nationality": "New Zealand",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": true,
      "price_cr": 0.6,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Kuldeep Sen",
      "role": "Bowler",
      "age": 27,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Sandeep Sharma",
      "role": "Bowler",
      "age": 31,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Nandre Burger",
      "role": "Bowler",
      "age": 27,
      "nationality": "South Africa",
      "batting_style": "Right Hand",
      "bowling_style": "Left Arm Fast",
      "is_overseas": true,
      "price_cr": 2.2,
      "is_captain": false,
      "is_retained": false
    }
  ],
  "Gujarat Titans": [
    {
      "player": "Shubman Gill",
      "role": "Batsman",
      "age": 26,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 17.5,
      "is_captain": true,
      "is_retained": true
    },
    {
      "player": "Jos Buttler",
      "role": "WK-Batsman",
      "age": 34,
      "nationality": "England",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": true,
      "price_cr": 15.75,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Kumar Kushagra",
      "role": "WK-Batsman",
      "age": 22,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 7.5,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Anuj Rawat",
      "role": "WK-Batsman",
      "age": 24,
      "nationality": "India",
      "batting_style": "Left Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Tom Banton",
      "role": "WK-Batsman",
      "age": 26,
      "nationality": "England",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": true,
      "price_cr": 0.75,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Glenn Phillips",
      "role": "Batsman",
      "age": 28,
      "nationality": "New Zealand",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": true,
      "price_cr": 1.2,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Nishant Sindhu",
      "role": "Allrounder",
      "age": 21,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Washington Sundar",
      "role": "Allrounder",
      "age": 25,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 3.2,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Mohd. Arshad Khan",
      "role": "Allrounder",
      "age": 26,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Sai Kishore",
      "role": "Bowler",
      "age": 28,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Left Arm Spin",
      "is_overseas": false,
      "price_cr": 4.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Jayant Yadav",
      "role": "Allrounder",
      "age": 34,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Jason Holder",
      "role": "Allrounder",
      "age": 33,
      "nationality": "West Indies",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": true,
      "price_cr": 2.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Sai Sudharsan",
      "role": "Batsman",
      "age": 24,
      "nationality": "India",
      "batting_style": "Left Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 8.5,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Shahrukh Khan",
      "role": "Batsman",
      "age": 30,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 7.4,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Kagiso Rabada",
      "role": "Bowler",
      "age": 30,
      "nationality": "South Africa",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast",
      "is_overseas": true,
      "price_cr": 10.75,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Mohammed Siraj",
      "role": "Bowler",
      "age": 31,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 12.25,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Prasidh Krishna",
      "role": "Bowler",
      "age": 29,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 10.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Manav Suthar",
      "role": "Bowler",
      "age": 25,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Left Arm Spin",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Gurnoor Singh Brar",
      "role": "Bowler",
      "age": 24,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Ishant Sharma",
      "role": "Bowler",
      "age": 36,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Ashok Sharma",
      "role": "Bowler",
      "age": 28,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Prithvi Raj Yarra",
      "role": "Bowler",
      "age": 24,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Luke Wood",
      "role": "Bowler",
      "age": 30,
      "nationality": "England",
      "batting_style": "Right Hand",
      "bowling_style": "Left Arm Fast Medium",
      "is_overseas": true,
      "price_cr": 0.5,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Rahul Tewatia",
      "role": "Allrounder",
      "age": 31,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Leg Break",
      "is_overseas": false,
      "price_cr": 11.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Rashid Khan",
      "role": "Bowler",
      "age": 27,
      "nationality": "Afghanistan",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Leg Break",
      "is_overseas": true,
      "price_cr": 18.0,
      "is_captain": false,
      "is_retained": true
    }
  ],
  "Punjab Kings": [
    {
      "player": "Shreyas Iyer",
      "role": "Batsman",
      "age": 30,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 26.75,
      "is_captain": true,
      "is_retained": true
    },
    {
      "player": "Nehal Wadhera",
      "role": "Batsman",
      "age": 26,
      "nationality": "India",
      "batting_style": "Left Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 4.2,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Vishnu Vinod",
      "role": "WK-Batsman",
      "age": 31,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 2.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Harnoor Pannu",
      "role": "Batsman",
      "age": 22,
      "nationality": "India",
      "batting_style": "Left Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Pyla Avinash",
      "role": "Batsman",
      "age": 23,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Prabhsimran Singh",
      "role": "WK-Batsman",
      "age": 24,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 4.0,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Shashank Singh",
      "role": "Batsman",
      "age": 33,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 5.25,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Marcus Stoinis",
      "role": "Allrounder",
      "age": 35,
      "nationality": "Australia",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": true,
      "price_cr": 11.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Harpreet Brar",
      "role": "Allrounder",
      "age": 28,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Left Arm Spin",
      "is_overseas": false,
      "price_cr": 5.75,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Marco Jansen",
      "role": "Allrounder",
      "age": 25,
      "nationality": "South Africa",
      "batting_style": "Left Hand",
      "bowling_style": "Left Arm Fast",
      "is_overseas": true,
      "price_cr": 13.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Azmatullah Omarzai",
      "role": "Allrounder",
      "age": 25,
      "nationality": "Afghanistan",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": true,
      "price_cr": 2.5,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Priyansh Arya",
      "role": "Allrounder",
      "age": 23,
      "nationality": "India",
      "batting_style": "Left Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 3.8,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Musheer Khan",
      "role": "Allrounder",
      "age": 20,
      "nationality": "India",
      "batting_style": "Left Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 2.25,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Suryansh Shedge",
      "role": "Allrounder",
      "age": 20,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Off Break",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Mitch Owen",
      "role": "Allrounder",
      "age": 25,
      "nationality": "Australia",
      "batting_style": "Left Hand",
      "bowling_style": "Left Arm Spin",
      "is_overseas": true,
      "price_cr": 0.75,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Cooper Connolly",
      "role": "Allrounder",
      "age": 22,
      "nationality": "Australia",
      "batting_style": "Left Hand",
      "bowling_style": "Left Arm Spin",
      "is_overseas": true,
      "price_cr": 1.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Ben Dwarshuis",
      "role": "Allrounder",
      "age": 31,
      "nationality": "Australia",
      "batting_style": "Left Hand",
      "bowling_style": "Left Arm Fast Medium",
      "is_overseas": true,
      "price_cr": 1.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Arshdeep Singh",
      "role": "Bowler",
      "age": 26,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Left Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 18.0,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Yuzvendra Chahal",
      "role": "Bowler",
      "age": 34,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Leg Break",
      "is_overseas": false,
      "price_cr": 18.0,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Vyshak Vijaykumar",
      "role": "Bowler",
      "age": 28,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast",
      "is_overseas": false,
      "price_cr": 4.2,
      "is_captain": false,
      "is_retained": true
    },
    {
      "player": "Yash Thakur",
      "role": "Bowler",
      "age": 26,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 1.5,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Xavier Bartlett",
      "role": "Bowler",
      "age": 27,
      "nationality": "Australia",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast",
      "is_overseas": true,
      "price_cr": 2.6,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Pravin Dubey",
      "role": "Bowler",
      "age": 26,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Leg Break",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Vishal Nishad",
      "role": "Bowler",
      "age": 23,
      "nationality": "India",
      "batting_style": "Right Hand",
      "bowling_style": "Left Arm Fast Medium",
      "is_overseas": false,
      "price_cr": 0.3,
      "is_captain": false,
      "is_retained": false
    },
    {
      "player": "Lockie Ferguson",
      "role": "Bowler",
      "age": 33,
      "nationality": "New Zealand",
      "batting_style": "Right Hand",
      "bowling_style": "Right Arm Fast",
      "is_overseas": true,
      "price_cr": 2.0,
      "is_captain": false,
      "is_retained": false
    }
  ]
};
